context:
  version: 0.1.5

package:
  name: mandown
  version: ${{ version }}

source:
  url: https://gitlab.com/kornelski/mandown/-/archive/${{ version }}/mandown-${{ version }}.tar.gz
  sha256: 32bf99a42dc7190733658a1beb7bc222d47441fbcb423905ca0fae2f3a32a87f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mandown --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Create man pages from markdown markup
  homepage: https://gitlab.com/kornelski/mandown
  repository: https://gitlab.com/kornelski/mandown

extra:
  recipe-maintainers:
    - danielnachun
